services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnetwork
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-cache
    networks:
      - appnetwork
    restart: always

  web:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - appnetwork
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studentdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

networks:
  appnetwork:
    driver: bridge

volumes:
  postgres_data: